name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: LMF-Manager-Windows
            output: dist/LMF-Export-Manager.exe

          - os: ubuntu-latest
            artifact: LMF-Manager-Linux
            output: dist/LMF-Export-Manager

          - os: macos-latest
            artifact: LMF-Manager-Mac-latest
            zip: LMF-Manager-Mac-latest.zip

          #- os: macos-11
          #  artifact: LMF-Manager-Mac-macos11
          #  zip: LMF-Manager-Mac-macos11.zip

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller


      # Windows
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --noconfirm --onefile --windowed --collect-all customtkinter --icon="icon.ico" --name "LMF-Export-Manager" generate_mit_gui.py

      # macOS + Linux
      - name: Build macOS / Linux
        if: matrix.os != 'windows-latest'
        run: |
          pyinstaller --noconfirm \
            --windowed \
            --collect-all customtkinter \
            --name "LMF-Export-Manager" \
            --icon="icon.ico" \
            generate_mit_gui.py

      - name: Zip macOS App
        if: startsWith(matrix.os, 'macos')
        run: |
          cd dist
          zip -r "../${{ matrix.zip }}" LMF-Export-Manager.app

      # Upload Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            ${{ matrix.output }}
            ${{ matrix.zip }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      # Nur die benötigten Dateien in einen Ordner kopieren
      - name: Prepare release files
        run: |
          mkdir release-files

          # Windows
          cp artifacts/LMF-Manager-Windows/LMF-Export-Manager.exe release-files/

          # Linux
          cp artifacts/LMF-Manager-Linux/LMF-Export-Manager release-files/

          # macOS
          cp artifacts/LMF-Manager-Mac-latest/LMF-Manager-Mac-latest.zip release-files/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
