name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: LMF-Manager-Windows
            zip: LMF-Manager-Windows-latest.zip
            #output: dist/LMF-Export-Manager.exe

          - os: ubuntu-latest
            artifact: LMF-Manager-Linux
            output: dist/LMF-Export-Manager

          - os: macos-latest
            artifact: LMF-Manager-Mac-latest
            zip: LMF-Manager-Mac-latest.zip

          #- os: macos-11
          #  artifact: LMF-Manager-Mac-macos11
          #  zip: LMF-Manager-Mac-macos11.zip

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller


      # Windows
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --noconfirm --windowed --collect-all customtkinter --icon="icon.ico" --name "LMF-Export-Manager" generate_mit_gui.py

      - name: Zip Windows Folder
        if: matrix.os == 'windows-latest'
        run: |
          $buildDir = "dist/LMF-Export-Manager"
          $zipPath = "${{ matrix.zip }}"

          # Lösche alte ZIP, falls vorhanden
          if (Test-Path $zipPath) { Remove-Item $zipPath }

          # Nur Dateien (EXE + DLLs), keine Unterordner wie INTERNAL
          $files = Get-ChildItem $buildDir -File
          Compress-Archive -Path $files.FullName -DestinationPath $zipPath

      # macOS + Linux
      - name: Build macOS / Linux
        if: matrix.os != 'windows-latest'
        run: |
          pyinstaller --noconfirm \
            --windowed \
            --collect-all customtkinter \
            --name "LMF-Export-Manager" \
            --icon="icon.ico" \
            generate_mit_gui.py

      - name: Zip macOS App
        if: startsWith(matrix.os, 'macos')
        run: |
          cd dist
          zip -r "../${{ matrix.zip }}" LMF-Export-Manager.app

      # Upload Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            ${{ matrix.output }}
            ${{ matrix.zip }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
